# Generated by Django 4.1.10 on 2023-07-31 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='is_good',
        ),
    ]
