# Generated by Django 4.1.10 on 2023-08-01 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_postlike_is_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subscribe_only',
        ),
    ]
