# Generated by Django 4.1.10 on 2023-08-11 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_title'),
        ('posts', '0005_alter_post_like_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='projects.project'),
        ),
    ]
