# Generated by Django 4.1.10 on 2023-08-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
    ]
