# Generated by Django 4.1.10 on 2023-08-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='e_mail',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
