# Generated by Django 4.2.3 on 2023-07-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
