# Generated by Django 4.2.3 on 2023-08-01 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile_image',
        ),
    ]
