# Generated by Django 4.1.10 on 2023-08-23 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscribe_uploader',
            },
        ),
        migrations.CreateModel(
            name='LikeImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.imagepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'like_image_post',
            },
        ),
        migrations.CreateModel(
            name='FollowUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follow_uploader',
            },
        ),
        migrations.CreateModel(
            name='BookmarkPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.IntegerField()),
                ('bookmark_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_prompt', to='search.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_prompt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmark_prompt',
            },
        ),
        migrations.CreateModel(
            name='BookmarkImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.imagepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmark_image_post',
            },
        ),
    ]
