# Generated by Django 4.1.10 on 2023-11-07 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_prompt', models.TextField(blank=True, null=True)),
                ('conflict_prompt', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_recommend', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prompt_recommend',
            },
        ),
    ]
