# Generated by Django 4.1.10 on 2023-08-23 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.IntegerField()),
                ('bookmark_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bookmark_prompt',
                'managed': False,
            },
        ),
    ]
