# Generated by Django 4.1.10 on 2023-08-23 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_bookmarkprompt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarkprompt',
            options={},
        ),
    ]
