# Generated by Django 4.1.10 on 2023-07-27 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_alter_followuploader_uploader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeimagepost',
            name='like_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
