# Generated by Django 4.1.10 on 2023-07-28 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0003_likeimagepost_like_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followuploader',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='subscribeuploader',
            name='subscribe',
        ),
        migrations.AddField(
            model_name='followuploader',
            name='follow_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscribeuploader',
            name='subscribe_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
