# Generated by Django 4.1.10 on 2023-08-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0003_alter_bookmarkprompt_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookmarkPrompt',
        ),
    ]
