# Generated by Django 4.1.10 on 2023-08-23 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0001_initial'),
        ('follows', '0004_delete_bookmarkprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.IntegerField()),
                ('bookmark_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_prompt', to='search.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_prompt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmark_prompt',
            },
        ),
    ]
