# Generated by Django 4.1.10 on 2023-08-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_rename_postlike_channelpostlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelpost',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
