# Generated by Django 4.1.10 on 2023-07-31 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='is_good',
        ),
    ]
