# Generated by Django 4.2.3 on 2023-08-01 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_rename_postlike_channelpostlike'),
        ('comments', '0003_remove_commentlike_is_good'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_comment', to='channel.channelpost')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_comment', to='comments.comment')),
            ],
            options={
                'db_table': 'channel_post_comment',
            },
        ),
    ]
