# Generated by Django 4.1.10 on 2023-08-23 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='e_mail',
            new_name='email',
        ),
    ]
