# Generated by Django 4.1.10 on 2023-08-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetable',
            name='image_file',
            field=models.CharField(max_length=255),
        ),
    ]
