# Generated by Django 4.1.10 on 2023-08-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_imagetable_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='thumbnail_image',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='imagetable',
            name='image_file',
            field=models.CharField(max_length=512),
        ),
    ]
