# Generated by Django 4.1.10 on 2023-07-25 04:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_imagetable_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprompt',
            name='prompt_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imageprompt',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt', to='images.imagetable'),
        ),
        migrations.AlterField(
            model_name='imagetable',
            name='cfg_scale',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='imagetable',
            name='clip_skip',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='imagetable',
            name='denoising_strength',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='imagetable',
            name='image_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imagetable',
            name='model_hash',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='imagetable',
            name='sampler',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='imagetable',
            name='seed',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='imagetable',
            name='steps',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
