# Generated by Django 4.1.10 on 2023-07-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_imagepostlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagePostLike',
        ),
    ]
