# Generated by Django 4.1.10 on 2023-08-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_channelpostcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
