# Generated by Django 4.1.10 on 2023-07-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='e_mail',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
