# Generated by Django 4.2.3 on 2023-07-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
