# Generated by Django 4.1.10 on 2023-07-27 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0005_imagepostlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.BooleanField(default=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_uploader', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscribe_uploader',
            },
        ),
        migrations.CreateModel(
            name='LikeImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=True)),
                ('image_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.imagepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'like_image_post',
            },
        ),
        migrations.CreateModel(
            name='FollowUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.BooleanField(default=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_uploader', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follow_uploader',
            },
        ),
        migrations.CreateModel(
            name='BookmarkImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark', models.BooleanField(default=True)),
                ('image_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.imagepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmark_image_post',
            },
        ),
    ]
