# Generated by Django 4.1.10 on 2023-07-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0004_remove_followuploader_follow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkimagepost',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='likeimagepost',
            name='likes',
        ),
    ]
