# Generated by Django 4.2.3 on 2023-07-31 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0005_remove_bookmarkimagepost_bookmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkimagepost',
            name='bookmark_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
