# Generated by Django 4.1.10 on 2023-08-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_subscribe_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
