# Generated by Django 4.1.10 on 2023-07-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
