# Generated by Django 4.1.10 on 2023-07-27 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0004_imageprompt_prompt_time_alter_imagepost_post_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_post_like_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_good', models.BooleanField(default=True)),
                ('image_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_post_like', to='images.imagepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_post_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'image_post_like',
            },
        ),
    ]
