# Generated by Django 4.2.3 on 2023-08-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('prompt', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('positive_weight', models.IntegerField(default=0)),
                ('negative_weight', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'prompt',
            },
        ),
    ]
