# Generated by Django 4.2.3 on 2023-08-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_prompt_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt_log',
            name='prompt_log_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
