# Generated by Django 4.1.10 on 2023-08-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt_rank',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField()),
            ],
            options={
                'db_table': 'prompt_rank',
            },
        ),
    ]
