# Generated by Django 4.2.3 on 2023-08-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_prompt_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prompt_log',
        ),
    ]
