# Generated by Django 4.2.3 on 2023-08-02 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0003_delete_prompt_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt_log',
            fields=[
                ('prompt_log_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prompt_log',
            },
        ),
    ]
