# Generated by Django 4.1.10 on 2023-08-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_prompt_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='prompt',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
