# Generated by Django 4.1.10 on 2023-08-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_prompt_log_prompt_log_id'),
        ('search', '0005_alter_prompt_prompt'),
    ]

    operations = [
    ]
